// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           21
// Async Callback (empty):               1
// Total number of exported functions:  24

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    identity
    (
        init => init
        upgrade => upgrade
        burnForTrust => burn_for_trust_endpoint
        migrateToTrust => migrate_to_trust_endpoint
        withdrawCostTokens => withdraw_cost_tokens_endpoint
        setAvatar => set_avatar_endpoint
        setAvatarAdmin => set_avatar_admin_endpoint
        removeAvatar => remove_avatar_endpoint
        getAvatar => get_avatar_view
        addManager => add_manager_endpoint
        removeManager => remove_manager_endpoint
        setCoreTokenBurnTrustMultiplier => set_core_token_burn_trust_multiplier_endpoint
        getCoreToken => core_token
        getRewardToken => reward_token
        getAvatarSetCost => cost_avatar_set
        getManagers => managers
        getCoreTokenBurnTrustMultiplier => core_token_burn_trust_multiplier
        setTrustStakeContract => set_trust_stake_contract_endpoint
        addTrust => add_trust_endpoint
        addTrustBatch => add_trust_batch_endpoint
        banUser => ban_user_endpoint
        restakeTrust => restake_trust_endpoint
        getTrustScore => get_trust_score
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
