// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            7
// Async Callback (empty):               1
// Total number of exported functions:   9

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    identity
    (
        init => init
        claimEgld => claim_egld_endpoint
        withdrawCostTokens => withdraw_cost_tokens_endpoint
        setAvatar => set_avatar_endpoint
        setAvatarAdmin => set_avatar_admin_endpoint
        removeAvatar => remove_avatar_endpoint
        getAvatar => get_avatar_view
        getAvatarSetCost => cost_avatar_set
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
